---
- name: ensure nginx is at the latest version
  apt: name=nginx state=latest
  become: yes
- name: start nginx
  service:
    name: nginx
    state: started
  become: yes
- name: Copy nginx configuration
  template: 
    src: default.conf
    dest: /etc/nginx/sites-available/{{ server_hostname }}.conf
  notify: restart nginx
- name: create symlink
  file:
    src: /etc/nginx/sites-available/{{ server_hostname }}.conf
    dest: /etc/nginx/sites-enabled/{{ server_hostname }}
    state: link
  become: yes
- name: Creates directory
  file:
    path: /var/www/{{ server_hostname }}
    state: directory
- name: copy the content of the web site
  template: 
    src: index.html
    dest: /var/www/{{ server_hostname }}/index.html
- name: restart nginx
  service:
    name: nginx
    state: restarted
  become: yes
